version: "3.8"

services:
  # Backend API
  facerecognitionbrain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/facerecognitionbrain-api
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/facerecognitionbrain-api
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/smart-brain
      REDIS_URI: redis://redis:6379

  # PostgresSQL
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_URL=postgres://admin:password@localhost:5432/smart-brain
      - POSTGRES_DB=smart-brain
      - POSTGRES_HOST=postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
