version: "3.8"

services:
  facerecognitionbrain-api:
    container_name: backend
    # image: node:alpine
    build: ./
    command: npm start
    working_dir: /usr/src/facerecognitionbrain-api
    ports:
      - "3000:3000"
